### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by marcotroisi** [microlib/acl#3]
We're trying to diversify our microservices languages. The reason for it is that we want to build a platform that runs well on a number of different languages, so that it integrates well with different applications which may be developed in any language.

I suggest we go with either Java or nodejs for this one. Everyone can say what their preference is.

***

My personal preference for this one would be Java. @luigizuccarelli is the Java master here, and he could easily build an initial working version.

**Comment by luigizuccarelli** [comment]
:+1:

**Comment by marcotroisi** [comment]
Then Java it is then.
